### ISSUE TITLE
Qwen tokenizer documentation is wrong (not applicable) for Qwen 1.5

### ISSUE THREAD

**Issue by Qubitium** [QwenLM/Qwen1.5#111]
In this doc post, Qwen talks about 205 (`<|extra_0-204|>`) extra tokens reserved to the end of the tokenizer vocab. However, manually checking the vocab.json and special token maps, none of the `<|extra_N|>` tokens are to be found. 

https://github.com/QwenLM/Qwen/blob/main/tokenization_note.md

Since BPE tokenizer is not easily resizable, we are at a loss how to add our custom tokens for Qwen 1.5 models for further training. Do the <|extra_N|> still exist but not mapped? If so what value (id ranges) should use for `<|extra_1-204|>`?

Can someone from the Qwen team elaborate on this since tokenization is critcial part of training and inference and updated documentation would be most welcome.  Thank you!

@JustinLin610  @huybery  @JianxinMa @jxst539246 

Edited:

Based on config.json and tokenizer_config.json Qwen 1.5 has max `151936 `(tokens) -  but largest used value is `151645 `so we have `151646 - 151935`  range to work with for custom use. Is this correct?

**Comment by jklj077** [comment]
The tokenizer implementation for Qwen and Qwen1.5 varies significantly, where the former employs a custom codebase utilizing `tiktoken`, while the latter is built upon the `transformers` library using either pure Python or the `tokenizers` package. Due to these inherent differences, it should be noted that not all features of `QwenTokenizer` are directly transferable to `Qwen2Tokenizer`.

Despite their structural disparities, both `QwenTokenizer` and `Qwen2Tokenizer` share a common characteristic: the index of the first unused token begins at 151646, counting from 0. Importantly, with the new codebase, the embedding size can be expanded flexibly to accommodate any additional tokens as needed.
