### ISSUE TITLE
some questions about construction of prompt for Qwen-MoE

### ISSUE THREAD

**Issue by cooper12121** [QwenLM/Qwen1.5#301]
i see you use <im__end>as eos_token, also in your code for target,you use target+<im_end>as label, but you also have the ```endoftext```token, so i want to know if i need to add ```endoftext```at the end of target. thank you

**Comment by JustinLin610** [comment]
for starters it is `<|im_end|>`.

check the chatml format to know more about the details. this token indicates the end of a turn. so when you train your model, since your model can learn to generate the token and thus it can be stopped at this token at the inference stage. therefore, it is somehow not that important whether to add an `<|endoftext|>` at the end or not for the chat model.
