### ISSUE TITLE
qwen110B-awq和千问72B不量化  那个效果好一点啊

### ISSUE THREAD

**Issue by yz-Python** [QwenLM/Qwen1.5#364]
请问一下    qwen110B-awq和千问72B全量  那个效果好一点啊
这两个部署的资源占用差不多

**Comment by jklj077** [comment]
Hey there,

I'd say, generally speaking, larger models tend to perform better across a broader range of tasks due to their increased capacity to understand and process complex information. However, benchmark results can sometimes be limited in reflecting every nuance. Ultimately, your personal experience with the models in your specific scenarios is what truly counts.

So, here's my advice: why not put these models to the test in your own environment? Run some experiments and see how they handle your unique tasks. If one of them fits like a glove, then go ahead and give it a spin! The choice should come down to practical performance in your context, so trust your judgment and find the one that best suits your needs. Happy testing!

**Comment by yz-Python** [comment]
thanks~
I'll give it a try. In terms of evaluation performance, they are quite similar, and the actual usage differences are also quite subtle.
