### ISSUE TITLE
Qwen1.5-7B-Chat推理，结果不一致

### ISSUE THREAD

**Issue by yecphaha** [QwenLM/Qwen1.5#409]
Qwen官方团队，你好，请教两个问题
Q1：用Qwen1.5-7B-Chat在做推理的时候，为什么会出现同一个问题，结果不一致的情况，temperature没有修改，设置为0。
Q2：为什么在推理的时候要用到set_seed这个参数呀，seed不是在训练的时候用的吗？

**Comment by jklj077** [comment]
Hello there!

Welcome to the exciting world of large language models! I'm assuming you're working with Hugging Face's transformers library (though other libraries work similarly). To get you up to speed, check out this insightful article: ["How to generate text: using different decoding methods for language generation with Transformers"](https://huggingface.co/blog/how-to-generate).

We've taken care to provide default generation parameters within the model files (found in `generation_config.json`, like this one: <https://huggingface.co/Qwen/Qwen1.5-72B-Chat/blob/main/generation_config.json>), to make it easier for beginners to start generating text right away. If you specify respective argument when calling `model.generate(...)`, it will override the default setting. By default, `do_sample` is set to `True`. 

A quick suggestion: Try running `model.generate(..., do_sample=False)` to see if the generated text remains significantly different. Please note that if you've set `temperature=0` in recent versions of `transformers`, an error might occur and you should always use `do_sample`.

When `do_sample` is `True`, the randomness in the generated text can mostly be controlled by setting the random number generator (RNG) seed. Transformers offers a handy utility function, `transformers.trainer_utils.set_seed`, which sets all relevant RNG seeds for you. With a fixed seed and sampling enabled, you should still obtain consistent generated text across runs.

Lastly, even with proper RNG setup, some randomness may still be present due to non-deterministic algorithms inherent in deep learning frameworks. The official PyTorch documentation briefly explains this at <https://pytorch.org/docs/stable/notes/randomness.html#avoiding-nondeterministic-algorithms>. Essentially, while computations are typically stable across devices and models, slight variations in results might occur.

I hope this clears up any confusion and helps you navigate the topic better!

**Comment by yecphaha** [comment]
> Hello there!
> 
> Welcome to the exciting world of large language models! I'm assuming you're working with Hugging Face's transformers library (though other libraries work similarly). To get you up to speed, check out this insightful article: ["How to generate text: using different decoding methods for language generation with Transformers"](https://huggingface.co/blog/how-to-generate).
> 
> We've taken care to provide default generation parameters within the model files (found in `generation_config.json`, like this one: https://huggingface.co/Qwen/Qwen1.5-72B-Chat/blob/main/generation_config.json), to make it easier for beginners to start generating text right away. If you specify respective argument when calling `model.generate(...)`, it will override the default setting. By default, `do_sample` is set to `True`.
> 
> A quick suggestion: Try running `model.generate(..., do_sample=False)` to see if the generated text remains significantly different. Please note that if you've set `temperature=0` in recent versions of `transformers`, an error might occur and you should always use `do_sample`.
> 
> When `do_sample` is `True`, the randomness in the generated text can mostly be controlled by setting the random number generator (RNG) seed. Transformers offers a handy utility function, `transformers.trainer_utils.set_seed`, which sets all relevant RNG seeds for you. With a fixed seed and sampling enabled, you should still obtain consistent generated text across runs.
> 
> Lastly, even with proper RNG setup, some randomness may still be present due to non-deterministic algorithms inherent in deep learning frameworks. The official PyTorch documentation briefly explains this at https://pytorch.org/docs/stable/notes/randomness.html#avoiding-nondeterministic-algorithms. Essentially, while computations are typically stable across devices and models, slight variations in results might occur.
> 
> I hope this clears up any confusion and helps you navigate the topic better!

非常感谢您的回复，还有一个问题，当 do_sample 为 True 时，设置的set_seed参数会应用在模型推理的哪个网络里，为什么固定种子和采样后，可以获得一致的生成文本，是因为每次推理，这个set_seed都是随机生成的吗？

**Comment by yecphaha** [comment]
> Hello there!
> 
> Welcome to the exciting world of large language models! I'm assuming you're working with Hugging Face's transformers library (though other libraries work similarly). To get you up to speed, check out this insightful article: ["How to generate text: using different decoding methods for language generation with Transformers"](https://huggingface.co/blog/how-to-generate).
> 
> We've taken care to provide default generation parameters within the model files (found in `generation_config.json`, like this one: https://huggingface.co/Qwen/Qwen1.5-72B-Chat/blob/main/generation_config.json), to make it easier for beginners to start generating text right away. If you specify respective argument when calling `model.generate(...)`, it will override the default setting. By default, `do_sample` is set to `True`.
> 
> A quick suggestion: Try running `model.generate(..., do_sample=False)` to see if the generated text remains significantly different. Please note that if you've set `temperature=0` in recent versions of `transformers`, an error might occur and you should always use `do_sample`.
> 
> When `do_sample` is `True`, the randomness in the generated text can mostly be controlled by setting the random number generator (RNG) seed. Transformers offers a handy utility function, `transformers.trainer_utils.set_seed`, which sets all relevant RNG seeds for you. With a fixed seed and sampling enabled, you should still obtain consistent generated text across runs.
> 
> Lastly, even with proper RNG setup, some randomness may still be present due to non-deterministic algorithms inherent in deep learning frameworks. The official PyTorch documentation briefly explains this at https://pytorch.org/docs/stable/notes/randomness.html#avoiding-nondeterministic-algorithms. Essentially, while computations are typically stable across devices and models, slight variations in results might occur.
> 
> I hope this clears up any confusion and helps you navigate the topic better!

您好，在[transformers/generation/utils.py](https://github.com/huggingface/transformers/blob/v4.40.2/src/transformers/generation/utils.py)代码里，do_sample (`bool`, *optional*, defaults to `False`)。

**Comment by jklj077** [comment]
The `AutoModelForXXX.from_pretrained` method will load the generation_config.json from model files and the settings will be overriden. For Qwen models, `do_sample` defaults to True.
