### ISSUE TITLE
why the base model can chat?

### ISSUE THREAD

**Issue by smallflyingpig** [QwenLM/Qwen1.5#419]
我们的base model是不是经过了SFT？
将base model的eos token改为<|im_end|>后，base就可以进行对话了，我们预训练也加入了SFT的数据？

**Comment by jklj077** [comment]
Please refer to Section 2.1 of the [Qwen Technical Report](https://arxiv.org/pdf/2309.16609):

> In recent studies (Zeng et al., 2022; Aribandi et al., 2021; Raffel et al., 2020), it has been demonstrated that pretraining language models with multi-task instructions can enhance their zero-shot and few-shot performance. To further enhance the performance of our model, we have incorporated high-quality instruction data into our pretraining process. To safeguard the integrity of our benchmark assessment, we have adopted a similar approach as Brown et al. (2020) and meticulously eliminated any instruction samples that exhibit a 13-gram overlap with any data present in the test sets utilized in our evaluation.

In Qwen(1.0), the instruction data have not been formatted with <|im_start|> and <|im_end|> in pre-training, and those tokens are unknown to the base model, which has been causing issue when users try to finetune the base models. In Qwen1.5, the issue is rectified.

As to your original question, the base model did not go through a separate phase of SFT but there are indeed instruction data formatted with ChatML in pretraining.
