### ISSUE TITLE
Qwen-7B量化4bit的预测结果问题

### ISSUE THREAD

**Issue by yecphaha** [QwenLM/Qwen1.5#420]
Qwen官方团队，您好，请教两个问题
Q1：Qwen-7B量化4bit的预测结果有可能会好于Qwen-7B原模型吗？
Q2：在模型推理的过程中，当 do_sample 为 True 时，设置的set_seed参数会应用在模型推理的哪个网络里，为什么固定seed和采样后，可以获得一致的生成文本，是因为每次推理，这个set_seed都是随机生成的吗？

**Comment by jklj077** [comment]
Hi,

1. Generally speaking, it should not occur, but there might be specific instances where it could happen.

2. I noticed that you've asked this same question previously on GitHub (<https://github.com/QwenLM/Qwen1.5/issues/409>). To avoid duplicate posts, let's focus here. The reason it wasn't answered earlier was because the question required some foundational understanding to be fully addressed. No worries though, as I'm happy to help clarify now!

   In the `transformers` library, `set_seed` isn't a parameter; instead, it's a useful function that initializes multiple random number generators (RNGs) with a specific starting point called a seed. These generators aren't truly random but rely on algorithms to create sequences of numbers that appear random — they are known as pseudorandom number generators (PRNGs). 

   When you provide the same seed value to a PRNG, it will consistently produce the exact same sequence of "random" numbers. 

   Now, these RNGs come into play during the sampling phase. The models predict a probability distribution over tokens, and the sampling process selects the token based on these probabilities. This selection process uses the RNGs. 

   So, when you set the seed using `set_seed`, and the RNGs generate the same series of random numbers, the outcome of the sampling process will also be identical. That means the sequence of tokens generated by the model would remain consistent for a given seed.
