### ISSUE TITLE
Inquiry on inconsistent vocab_size configurations across model sizes

### ISSUE THREAD

**Issue by ShangmingCai** [QwenLM/Qwen1.5#466]
Hello Qwen Team,

I've recently been conducting experiments with speculative decoding using the Qwen model series and encountered an issue related to the vocabulary size (vocab_size) in different model scales. I noticed that models with 7B parameters and below have a vocab_size of 151,936, whereas models with 14B parameters and above use a vocab_size of 152,064. This inconsistency has been causing some trouble during my experimentation.

Could you please explain the reasoning behind these different vocab_sizes configurations for the models? Additionally, are there any plans to standardize the vocab_size across all models in the upcoming Qwen 2.0 release?

If unifying the vocab_size is not possible, would the team consider training and releasing a smaller-scale draft model that is compatible with a 72B parameter model?

Any insights or information you could provide would be greatly appreciated.

**Comment by jklj077** [comment]
Hi, 

It has been explained many times and I would strongly suggest that you search through the issues.
- https://github.com/QwenLM/Qwen1.5/issues/29
- https://github.com/QwenLM/Qwen1.5/issues/147
- https://github.com/QwenLM/Qwen1.5/issues/292

I don't know what was causing your trouble, because you did not describe the actual issue. You can always resize the embedding, as the index over 151646 is meaningless.
