### ISSUE TITLE
我本地可以跑qwen1 的72b int4， 但是跑不了qwen1.5的72b int4

### ISSUE THREAD

**Issue by papandadj** [QwenLM/Qwen1.5#54]
就是会卡在
```py
generated_ids = model.generate(
    model_inputs.input_ids,
    max_new_tokens=512
)
```
我是用好多张4090的显卡来跑的，用qwen1大约占三个显卡，出token的速度还可以，用1.5直接卡在这里（感觉只用了一个显卡），1.5是不是不能使用多张显卡？

**Comment by coreyho** [comment]
same problem , 2XA100

**Comment by coreyho** [comment]
2*A100，vllm可以启动qwen-72b-chat，qwen1.5报错

ValueError: The model's max seq len (32768) is larger than the maximum number of tokens that can be stored in KV cache (4464). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.

**Comment by JustinLin610** [comment]
These are two questions.

First question is. Check our latest readme, add `torch_dtype='auto'` so that you can use bf16 for the inference. 

Second one is because vllm directly sets the maxlen by max pos emb, so follow its instruction and set --max_model_len to a lower value, say 1024 or something else.

**Comment by papandadj** [comment]
现在可以了，我用ollama来跑了
