### ISSUE TITLE
load model error: Both attn_implementation="sdpa" and `use_flash_attention_2=True` were used when loading the model, which are not compatible. We recommend to just use `attn_implementation="flash_attention_2"` when loading the model.

### ISSUE THREAD

**Issue by lucasjinreal** [QwenLM/Qwen1.5#56]
Support V100 please.
load model error: Both attn_implementation="sdpa" and `use_flash_attention_2=True` were used when loading the model, which are not compatible. We recommend to just use `attn_implementation="flash_attention_2"` when loading the model.

**Comment by jklj077** [comment]
I think you were mixing things up:

1. `AutoModelForCasualLM.from_pretrained(..., torch_dtype=torch.float16, attn_implementation="flash_attention_2")`: It will use the standalone `flash-attn` package and the compatibility support from `transformers`. However, the standalone `flash-attn` does not support V100 , so errors are expected.

2. `AutoModelForCasualLM.from_pretrained(..., torch_dtype=torch.float16, attn_implementation="sdpa")`: It will use the `scaled_dot_product_attention` method from `torch` and the compatibility support from `transformers`. The `scaled_dot_product_attention` method has multiple backend implementation and flash attention is one of them since torch 2.2. It can by controlled by using the `torch.backends.cuda.sdp_kernel` context

   ```python
   with torch.backends.cuda.sdp_kernel(enable_flash=True, enable_math=False, enable_mem_efficient=False):
       model.generate(xxx)
   ```

   It should work on V100 but you will need a newer version of torch.

**Comment by fclearner** [comment]
v100 is using memory efficient attention, refer to: https://www.cnblogs.com/51zone/p/18101087
